### PR TITLE
Correct the error where the MPC comparison result is empty. 

### PR DESCRIPTION
**Pull request by Keepmoving-ZXY**
1.The arithmetic component initially supported MPC comparison only for integer columns, but now it supports both integer and float columns.
2.The arithmetic component previously only supported column names consisting of a single character, this has been fixed.
3.The arithmetic component previously did not support comparison of columns with differing data types, this issue has been resolved.

### CODE REVIEW

**Comment by mi-sery** [comment]
我已阅读 CLA 文件并特此签署 CLA

**Comment by mi-sery** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mi-sery** [comment]
recheck

**Comment by mi-sery** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/primihub/.github/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> **1** out of **2** committers have signed the CLA.✅ @Keepmoving-ZXY❌ @mi-seryYou can retrigger this bot by commenting **recheck** in this Pull Request
I have read the CLA Document and I hereby sign the CLA

**Review by phoenix20162016 — APPROVED** [review]

**Review by yankaili2006 — APPROVED** [review]

**Review by yankaili2006 — APPROVED** [review]

**Pull request merged**
